# Generated by Django 4.1 on 2022-10-11 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="post", new_name="posting",),
    ]
