# Generated by Django 4.1 on 2022-10-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cover",
            field=models.ImageField(
                default="/image/cover.png", upload_to="cover-images"
            ),
        ),
        migrations.AlterField(
            model_name="posting",
            name="post",
            field=models.ImageField(blank=True, null=True, upload_to="post"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="dp",
            field=models.ImageField(
                default="/image/profile.png", upload_to="profile-images"
            ),
        ),
    ]
