# Generated by Django 4.1 on 2022-10-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_profile_cover_alter_posting_post_alter_profile_dp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="cover",
            field=models.ImageField(default="cover.jpg", upload_to="cover-images"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="dp",
            field=models.ImageField(default="profile.png", upload_to="profile-images"),
        ),
    ]
