# Generated by Django 4.1 on 2022-10-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_follow"),
    ]

    operations = [
        migrations.CreateModel(
            name="like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
            ],
        ),
    ]
