# Generated by Django 4.1 on 2022-10-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_like"),
    ]

    operations = [
        migrations.CreateModel(
            name="comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.CharField(max_length=100)),
                ("comment", models.TextField(max_length=100)),
                ("person", models.CharField(max_length=100)),
            ],
        ),
    ]
