# Generated by Django 4.1 on 2022-10-14 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.posting"
            ),
        ),
    ]
